name: deploy_s3
on: push
jobs:
  deploy:
    runs-on : ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - name: aws login
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          audience: sts.amazonaws.com.cn
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::899042279834:role/gitops_aws_access
      
  
