name: test_output
on: 
  workflow_dispatch:
jobs:
  build:
    outputs:
      version: ${{steps.image_version.outputs.version}}
    runs-on: ubuntu-24.04
    steps:
       - name: set image_version
         id : image_version
         run: |
           echo "version=v1.0.1" >> $GITHUB.OUTPUT
       - name: get version in steps
         run: |
           echo "diff step ${{steps.image_version.output.version}}"
      
  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: get image_version
        run: |
            echo "image version is ${{ needs.build.outputs.version }}" 
      
        
